// Code generated by "stringer -type=Button"; DO NOT EDIT

package redbutton

import "fmt"

const _Button_name = "UnknownClosedPressedArmed"

var _Button_index = [...]uint8{0, 7, 13, 20, 25}

func (i Button) String() string {
	if i < 0 || i >= Button(len(_Button_index)-1) {
		return fmt.Sprintf("Button(%d)", i)
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
